name: Auto Dashboard

on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch Linear Data
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
        run: |
          curl -X POST https://api.linear.app/graphql \
          -H "Content-Type: application/json" \
          -H "Authorization: $LINEAR_API_KEY" \
          -d '{
            "query":"{
              issues(first:20){
                nodes{
                  title
                  description
                  createdAt
                  state{
                    name
                  }
                }
              }
            }"
          }' > linear-data.json

      - name: Save Linear Data
        run: |
          {
            echo 'LINEAR_DATA<<EOF'
            cat linear-data.json
            echo EOF
          } >> $GITHUB_ENV

      - name: Generate Dashboard
        run: node generate.js

      - name: Debug HTML
        run: cat dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
